// <auto-generated />
using System;
using DAL.VehicleServerService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(VehicleServerContext))]
    partial class VehicleServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("MODELS.ErrorHAndling.ExcpetionError", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ExceptionErrors");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.Datalogger", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataloggerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataloggerTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DataloggerTypeID");

                    b.ToTable("Dataloggers");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.DataloggerType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanChannels")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemoryStorage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DataloggerTypes");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.Server", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP_URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerCredentialsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerTypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ServerCredentialsID");

                    b.HasIndex("ServerTypeID");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.ServerCredentials", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ServerCredentials");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.ServerType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ServerTypes");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataloggerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DataloggerID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.Datalogger", b =>
                {
                    b.HasOne("MODELS.VehicleServerInfo.DataloggerType", "DataloggerType")
                        .WithMany()
                        .HasForeignKey("DataloggerTypeID");
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.Server", b =>
                {
                    b.HasOne("MODELS.VehicleServerInfo.ServerCredentials", "ServerCredentials")
                        .WithMany()
                        .HasForeignKey("ServerCredentialsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELS.VehicleServerInfo.ServerType", "ServerType")
                        .WithMany()
                        .HasForeignKey("ServerTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MODELS.VehicleServerInfo.Vehicle", b =>
                {
                    b.HasOne("MODELS.VehicleServerInfo.Datalogger", "Datalogger")
                        .WithMany()
                        .HasForeignKey("DataloggerID");
                });
#pragma warning restore 612, 618
        }
    }
}
